import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'

/**
 * GET /api/templates/[id]/last-instructions
 *
 * Returns the do/don't instructions from the most recent output
 * generated by the current user with this template.
 */
export async function GET(
  request: Request,
  { params }: { params: { id: string } }
) {
  try {
    const supabase = await createClient()

    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { data: output } = await supabase
      .from('outputs')
      .select('do_instructions, dont_instructions')
      .eq('template_id', params.id)
      .eq('created_by', user.id)
      .order('created_at', { ascending: false })
      .limit(1)
      .single()

    if (!output) {
      return NextResponse.json({ doInstructions: '', dontInstructions: '' })
    }

    return NextResponse.json({
      doInstructions: output.do_instructions || '',
      dontInstructions: output.dont_instructions || '',
    })
  } catch {
    return NextResponse.json({ doInstructions: '', dontInstructions: '' })
  }
}
